openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: Simple test API for web UI testing
servers:
  - url: https://api.example.com/v1
paths:
  /users:
    get:
      summary: Get users
      operationId: getUsers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
        '500':
          description: Server error
    post:
      summary: Create user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Bad request
        '500':
          description: Server error
